import type { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    _id: "1",
    name: "MacBook Pro 16\" M4 Max",
    slug: "macbook-pro-16-m4-max",
    description: "The most powerful MacBook Pro ever with M4 Max chip, 48GB unified memory, and 1TB SSD. Featuring a stunning 16.2-inch Liquid Retina XDR display.",
    categoryId: "cat-laptops",
    price: 3499,
    compareAtPrice: 3799,
    stock: 15,
    images: [],
    specifications: { Chip: "M4 Max", Memory: "48GB", Storage: "1TB SSD", Display: "16.2\" Liquid Retina XDR" },
    brand: "Apple",
    featured: true,
    status: "published",
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-03-01"),
  },
  {
    _id: "2",
    name: "iPhone 16 Pro Max",
    slug: "iphone-16-pro-max",
    description: "The ultimate iPhone with A18 Pro chip, 48MP pro camera system, and all-day battery life. Titanium design in four stunning finishes.",
    categoryId: "cat-smartphones",
    price: 1199,
    compareAtPrice: 1299,
    stock: 42,
    images: [],
    specifications: { Chip: "A18 Pro", Storage: "256GB", Display: "6.9\" Super Retina XDR", Camera: "48MP Triple" },
    brand: "Apple",
    featured: true,
    status: "published",
    createdAt: new Date("2025-09-20"),
    updatedAt: new Date("2026-02-15"),
  },
  {
    _id: "3",
    name: "NVIDIA GeForce RTX 5090",
    slug: "nvidia-rtx-5090",
    description: "The flagship Blackwell GPU with 32GB GDDR7 VRAM. Revolutionary AI-powered neural rendering and real-time ray tracing at 4K 240fps.",
    categoryId: "cat-components",
    price: 1999,
    compareAtPrice: undefined,
    stock: 8,
    images: [],
    specifications: { VRAM: "32GB GDDR7", Architecture: "Blackwell", Cores: "21,760", Power: "575W" },
    brand: "NVIDIA",
    featured: true,
    status: "published",
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2026-03-10"),
  },
  {
    _id: "4",
    name: "Samsung Galaxy S26 Ultra",
    slug: "samsung-galaxy-s26-ultra",
    description: "Samsung's most advanced smartphone with Snapdragon 8 Gen 5, 200MP camera, S Pen integration, and Galaxy AI.",
    categoryId: "cat-smartphones",
    price: 1399,
    compareAtPrice: 1499,
    stock: 27,
    images: [],
    specifications: { Chip: "Snapdragon 8 Gen 5", Storage: "512GB", Display: "6.9\" Dynamic AMOLED 2X", Camera: "200MP Quad" },
    brand: "Samsung",
    featured: false,
    status: "published",
    createdAt: new Date("2026-02-10"),
    updatedAt: new Date("2026-03-05"),
  },
  {
    _id: "5",
    name: "Dell XPS 16",
    slug: "dell-xps-16",
    description: "Redesigned XPS with Intel Core Ultra 9, NVIDIA RTX 5070, and a gorgeous 4K OLED InfinityEdge display. Premium ultrabook perfection.",
    categoryId: "cat-laptops",
    price: 2499,
    compareAtPrice: 2699,
    stock: 19,
    images: [],
    specifications: { CPU: "Core Ultra 9 285H", GPU: "RTX 5070", Memory: "32GB", Storage: "1TB SSD", Display: "16\" 4K OLED" },
    brand: "Dell",
    featured: true,
    status: "published",
    createdAt: new Date("2026-01-25"),
    updatedAt: new Date("2026-03-08"),
  },
  {
    _id: "6",
    name: "AMD Ryzen 9 10950X",
    slug: "amd-ryzen-9-10950x",
    description: "24 cores, 48 threads of Zen 6 power. The ultimate workstation CPU for content creation, rendering, and scientific computing.",
    categoryId: "cat-components",
    price: 799,
    compareAtPrice: 899,
    stock: 35,
    images: [],
    specifications: { Cores: "24", Threads: "48", Base: "4.5 GHz", Boost: "6.2 GHz", TDP: "170W" },
    brand: "AMD",
    featured: false,
    status: "published",
    createdAt: new Date("2025-11-15"),
    updatedAt: new Date("2026-02-20"),
  },
  {
    _id: "7",
    name: "Sony WH-1000XM6",
    slug: "sony-wh-1000xm6",
    description: "Industry-leading noise cancellation reimagined. Adaptive Sound Control, 40-hour battery, and Hi-Res Audio Wireless.",
    categoryId: "cat-accessories",
    price: 399,
    compareAtPrice: 449,
    stock: 64,
    images: [],
    specifications: { Driver: "30mm", Battery: "40 hours", Codec: "LDAC", Weight: "254g" },
    brand: "Sony",
    featured: false,
    status: "published",
    createdAt: new Date("2025-10-05"),
    updatedAt: new Date("2026-01-20"),
  },
  {
    _id: "8",
    name: "Logitech G Pro X Superlight 3",
    slug: "logitech-g-pro-x-superlight-3",
    description: "The lightest and fastest Logitech G mouse ever. Under 50g with HERO 4 sensor, 8K polling, and LIGHTFORCE hybrid switches.",
    categoryId: "cat-peripherals",
    price: 179,
    compareAtPrice: undefined,
    stock: 103,
    images: [],
    specifications: { Sensor: "HERO 4", Weight: "48g", Polling: "8000Hz", Battery: "95 hours" },
    brand: "Logitech",
    featured: false,
    status: "published",
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-15"),
  },
  {
    _id: "9",
    name: "ASUS ROG Swift OLED PG49WCD",
    slug: "asus-rog-swift-oled-pg49wcd",
    description: "49-inch super-ultrawide OLED gaming monitor. Dual QHD resolution, 240Hz refresh rate, 0.03ms response time.",
    categoryId: "cat-peripherals",
    price: 1499,
    compareAtPrice: 1699,
    stock: 12,
    images: [],
    specifications: { Size: "49\"", Panel: "OLED QD-OLED", Resolution: "5120x1440", Refresh: "240Hz", Response: "0.03ms" },
    brand: "ASUS",
    featured: true,
    status: "published",
    createdAt: new Date("2026-02-28"),
    updatedAt: new Date("2026-03-12"),
  },
  {
    _id: "10",
    name: "AirPods Max 2",
    slug: "airpods-max-2",
    description: "Reengineered over-ear headphones with H3 chip, adaptive audio, USB-C, and 40-hour battery life. Five stunning colors.",
    categoryId: "cat-accessories",
    price: 549,
    compareAtPrice: 599,
    stock: 31,
    images: [],
    specifications: { Chip: "H3", Battery: "40 hours", Connectivity: "USB-C, Bluetooth 5.4", Weight: "385g" },
    brand: "Apple",
    featured: false,
    status: "published",
    createdAt: new Date("2025-09-10"),
    updatedAt: new Date("2026-01-30"),
  },
  {
    _id: "11",
    name: "SteelSeries Apex Pro TKL (2026)",
    slug: "steelseries-apex-pro-tkl-2026",
    description: "OmniPoint 3.0 adjustable magnetic switches with per-key actuation. Fastest typing and gaming keyboard ever made.",
    categoryId: "cat-peripherals",
    price: 249,
    compareAtPrice: undefined,
    stock: 57,
    images: [],
    specifications: { Switches: "OmniPoint 3.0", Layout: "TKL", Connectivity: "USB-C / Bluetooth / 2.4GHz", Battery: "45 hours" },
    brand: "SteelSeries",
    featured: false,
    status: "published",
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-02-18"),
  },
  {
    _id: "12",
    name: "Corsair Dominator Titanium DDR6",
    slug: "corsair-dominator-titanium-ddr6",
    description: "Next-gen DDR6 memory with 9600MT/s speeds. Patented DHX cooling technology with customizable RGB lighting.",
    categoryId: "cat-components",
    price: 329,
    compareAtPrice: 379,
    stock: 22,
    images: [],
    specifications: { Capacity: "32GB (2x16GB)", Speed: "9600MT/s", Latency: "CL38", Voltage: "1.4V" },
    brand: "Corsair",
    featured: false,
    status: "published",
    createdAt: new Date("2026-03-05"),
    updatedAt: new Date("2026-03-14"),
  },
];
