export const env = {
  mongodbUri: process.env.MONGODB_URI,
  clerkSecretKey: process.env.CLERK_SECRET_KEY,
  clerkPublishableKey: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  rustfsUrl: process.env.RUSTFS_URL,
  rustfsSecretKey: process.env.RUSTFS_SECRET_KEY,
  signInUrl: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL || "/sign-in",
  signUpUrl: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL || "/sign-up",
  afterSignInUrl: process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL || "/",
  afterSignUpUrl: process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL || "/",
  plunkSecretKey: process.env.PLUNK_SECRET_KEY,
  plunkPublicKey: process.env.NEXT_PUBLIC_PLUNK_PUBLIC_KEY,
  contactEmail: process.env.CONTACT_EMAIL,
  baseUrl: process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000",
} as const;
